# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BASE_URL": "00_core.constants.ipynb",
         "RELEASES_URL": "00_core.constants.ipynb",
         "VALID_CURR_ABBR": "00_core.constants.ipynb",
         "UserWithUserTokenBasedAuthentication": "01_core.discogs_user.ipynb",
         "get_release": "02_core.database_rq.ipynb",
         "get_release_rating_by_user": "02_core.database_rq.ipynb"}

modules = ["core/constants.py",
           "core/discogs_user.py",
           "core/database_rq.py"]

doc_url = "https://cpow-89.github.io/pydiscogs/"

git_url = "https://github.com/cpow-89/pydiscogs/tree/master/"

def custom_doc_links(name): return None
