# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://cpow-89.github.io/pydiscogs/"

git_url = "https://github.com/cpow-89/pydiscogs/tree/master/"

def custom_doc_links(name): return None
