# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BASE_URL": "00_core.ipynb",
         "UserWithUserTokenBasedAuthentication": "00_core.ipynb",
         "get_release": "01_discogs_requests.database.ipynb"}

modules = ["core.py",
           "discogs_requests/database.py"]

doc_url = "https://cpow-89.github.io/pydiscogs/"

git_url = "https://github.com/cpow-89/pydiscogs/tree/master/"

def custom_doc_links(name): return None
