# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BASE_URL": "00_core.constants.ipynb",
         "RELEASES_URL": "00_core.constants.ipynb",
         "MASTERS_URL": "00_core.constants.ipynb",
         "ARTIST_URL": "00_core.constants.ipynb",
         "LABEL_URL": "00_core.constants.ipynb",
         "VALID_CURR_ABBR": "00_core.constants.ipynb",
         "VALID_SORT_OPTIONS_MASTERS": "00_core.constants.ipynb",
         "VALID_SORT_OPTIONS_ARTIST": "00_core.constants.ipynb",
         "VALID_SORT_ORDER": "00_core.constants.ipynb",
         "UserWithoutAuthentication": "01_core.discogs_user.ipynb",
         "UserWithUserTokenBasedAuthentication": "01_core.discogs_user.ipynb",
         "get_release": "02_core.database_rq.ipynb",
         "get_release_rating_by_user": "02_core.database_rq.ipynb",
         "update_release_rating_for_given_user": "02_core.database_rq.ipynb",
         "delete_release_rating_by_user": "02_core.database_rq.ipynb",
         "get_release_rating_by_community": "02_core.database_rq.ipynb",
         "get_master_release": "02_core.database_rq.ipynb",
         "get_releases_related_to_master_release": "02_core.database_rq.ipynb",
         "get_artist": "02_core.database_rq.ipynb",
         "get_artist_releases": "02_core.database_rq.ipynb",
         "get_label": "02_core.database_rq.ipynb"}

modules = ["core/constants.py",
           "core/discogs_user.py",
           "core/database_rq.py"]

doc_url = "https://cpow-89.github.io/discogspy/"

git_url = "https://github.com/cpow-89/discogspy/tree/master/"

def custom_doc_links(name): return None
