# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_core.database_rq.ipynb (unless otherwise specified).

__all__ = ['get_release']

# Cell
import requests
from typing import Union
from . import *

# Cell
def get_release(user:UserWithUserTokenBasedAuthentication,
                release_id:int,
                curr_abbr=Union[str, None])->requests.models.Response:
    """Get information to a particular release from discogs database.
       A release represents a particular physical or digital object released by
       one or more Artists."""
    url = f"{BASE_URL}/releases/{release_id}"
    headers = user.headers
    params = {"token": user.user_token}
    if curr_abbr:
        params["curr_addr"] = curr_abbr
    return requests.get(url, headers=headers, params=params)