# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_core.database_rq.ipynb (unless otherwise specified).

__all__ = ['get_release']

# Cell
import requests
from . import *

# Cell
def get_release(user, release_id, curr_abbr=None):
    url = f"{BASE_URL}/releases/{release_id}"
    headers = user.headers
    params = {"token": user.user_token}
    if curr_abbr:
        params["curr_addr"] = curr_abbr
    return requests.get(url, headers=headers, params=params)