# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.discogs_user.ipynb (unless otherwise specified).

__all__ = ['UserWithUserTokenBasedAuthentication']

# Cell
class UserWithUserTokenBasedAuthentication(object):
    """A wrapper for information about an user with user token based authentication"""
    def __init__(self, user_token, user_agent):
        self.user_token = user_token
        self.headers = {
            "Accept": "json",
            "Accept-Encoding": "gzip",
            "User-Agent": user_agent
        }