# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.constants.ipynb (unless otherwise specified).

__all__ = ['BASE_URL', 'RELEASES_URL', 'MASTERS_URL', 'VALID_CURR_ABBR']

# Cell
BASE_URL = "https://api.discogs.com"
RELEASES_URL = f"{BASE_URL}/releases"
MASTERS_URL = f"{BASE_URL}/masters"

"""Valid currencies for marketplace data"""
VALID_CURR_ABBR = ["USD", "GBP", "EUR", "CAD", "AUD", "JPY",
                   "CHF", "MXN", "BRL", "NZD", "SEK", "ZAR"]