# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_core.database_rq.ipynb (unless otherwise specified).

__all__ = ['get_release', 'get_release_rating_by_user']

# Cell
import requests
from typing import Union
from . import *

# Cell
def get_release(user:Union[UserWithoutAuthentication,
                           UserWithUserTokenBasedAuthentication],
                release_id:int,
                curr_abbr=Union[str, None])->requests.models.Response:
    """
    Get information to a particular release from discogs database.
    A release represents a particular physical or digital object released by
    one or more Artists.

    No user Authentication needed.
    """
    url = f"{RELEASES_URL}/{release_id}"
    headers = user.headers
    params = user.params
    if curr_abbr and curr_abbr in VALID_CURR_ABBR:
        params["curr_addr"] = curr_abbr
    return requests.get(url, headers=headers, params=params)

# Cell
def get_release_rating_by_user(user:Union[UserWithoutAuthentication,
                                          UserWithUserTokenBasedAuthentication],
                               release_id:int,
                               username=str)->requests.models.Response:
    """
    Get the rating of a release for a given user.

    No user Authentication needed.
    """
    url = f"{RELEASES_URL}/{release_id}/rating/{username}"
    headers = user.headers
    params = user.params
    return requests.get(url, headers=headers, params=params)