# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_core.rq_collection.ipynb (unless otherwise specified).

__all__ = ['get_user_collection_folders', 'create_new_user_collection_folder', 'get_folder_metadata',
           'change_collection_folder_name', 'delete_collection_folder', 'get_collection_folder_by_release']

# Cell
import requests
from typing import Union
from . import *

# Cell


def get_user_collection_folders(user: Union[UserWithoutAuthentication,
                                      UserWithUserTokenBasedAuthentication],
                                username: str) -> requests.models.Response:
    """
    Get a list of folders in a user’s collection.

    Note: If you are not authenticated as the collection owner,
          only folder ID 0 (the “All” folder) will be visible (if the requested user’s collection is public).

    No user Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/folders"
    headers = user.headers
    params = user.params

    return requests.get(url, headers=headers, params=params)

# Cell


def create_new_user_collection_folder(user: UserWithUserTokenBasedAuthentication,
                                      username: str,
                                      folder_name: str) -> requests.models.Response:
    """
    Create a new folder in a user’s collection.

    User Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/folders"

    params = user.params

    data = {"name": folder_name}

    return requests.post(url, params=params, json=data)

# Cell


def get_folder_metadata(user: Union[UserWithoutAuthentication,
                                    UserWithUserTokenBasedAuthentication],
                        username: str,
                        folder_id: int) -> requests.models.Response:
    """
    Get metadata about a folder in a user’s collection.

    Note: If folder_id is not 0, authentication as the collection owner is required.

    No user Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/folders/{folder_id}"
    headers = user.headers
    params = user.params

    return requests.get(url, headers=headers, params=params)

# Cell


def change_collection_folder_name(user: UserWithUserTokenBasedAuthentication,
                                  username: str,
                                  folder_id: int,
                                  new_folder_name: str) -> requests.models.Response:
    """
    Change the name of an existing collection folder in a user’s collection.

    User Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/folders/{folder_id}"
    params = user.params

    data = {"name": new_folder_name}

    return requests.post(url, params=params, json=data)

# Cell


def delete_collection_folder(user: UserWithUserTokenBasedAuthentication,
                             username: str,
                             folder_id: int
                             ) -> requests.models.Response:
    """
    Delete an existing collection folder from a user’s collection.

    User Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/folders/{folder_id}"
    headers = user.headers
    params = user.params

    return requests.delete(url, headers=headers, params=params)

# Cell


def get_collection_folder_by_release(user: UserWithUserTokenBasedAuthentication,
                                     username: str,
                                     release_id: int,
                                     page: Union[int, None] = None,
                                     per_page: Union[int, None] = None,
                                     ) -> requests.models.Response:
    """
    Get the user’s collection folders which contain a specified release.

    User Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/releases/{release_id}"
    headers = user.headers
    params = user.params

    if page:
        params["page"] = max(1, page)
    if per_page:
        params["per_page"] = max(1, per_page)

    return requests.get(url, headers=headers, params=params)