# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_core.rq_collection.ipynb (unless otherwise specified).

__all__ = ['get_user_collection_folders', 'create_new_user_collection_folder', 'get_folder_metadata']

# Cell
import requests
from typing import Union
from . import *

# Cell


def get_user_collection_folders(user: Union[UserWithoutAuthentication,
                                      UserWithUserTokenBasedAuthentication],
                                username: str) -> requests.models.Response:
    """
    Get a list of folders in a user’s collection.

    Note: If you are not authenticated as the collection owner,
          only folder ID 0 (the “All” folder) will be visible (if the requested user’s collection is public).

    No user Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/folders"
    headers = user.headers
    params = user.params

    return requests.get(url, headers=headers, params=params)

# Cell


def create_new_user_collection_folder(user: UserWithUserTokenBasedAuthentication,
                                      username: str,
                                      folder_name: str) -> requests.models.Response:
    """
    Create a new folder in a user’s collection.

    User Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/folders"

    params = user.params

    data = {"name": folder_name}

    return requests.post(url, params=params, json=data)

# Cell


def get_folder_metadata(user: Union[UserWithoutAuthentication,
                                    UserWithUserTokenBasedAuthentication],
                        username: str,
                        folder_id: int) -> requests.models.Response:
    """
    Get metadata about a folder in a user’s collection.

    Note: If folder_id is not 0, authentication as the collection owner is required.

    No user Authentication needed.
    """

    url = f"{USERS_URL}/{username}/collection/folders/{folder_id}"
    headers = user.headers
    params = user.params

    return requests.get(url, headers=headers, params=params)