# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_core.rq_inventory_export.ipynb (unless otherwise specified).

__all__ = ['request_inventory_export']

# Cell
import requests
from typing import Union
from . import *

# Cell


def request_inventory_export(user: UserWithUserTokenBasedAuthentication) -> requests.models.Response:
    """
    Request an export of your inventory as a CSV.

    User Authentication needed.
    """
    url = f"{INVENTORY_EXPORT_URL}"
    headers = user.headers
    params = user.params

    return requests.post(url, headers=headers, params=params)