# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_core.rq_wantlist.ipynb (unless otherwise specified).

__all__ = ['get_user_wantlist']

# Cell
import requests
from typing import Union
from . import *

# Cell


def get_user_wantlist(user: Union[UserWithoutAuthentication,
                                  UserWithUserTokenBasedAuthentication],
                      username: str,
                      page: Union[int, None] = None,
                      per_page: Union[int, None] = None,
                      ) -> requests.models.Response:
    """
    Get a list of releases from the wantlist of a given user.

    Note: If the wantlist has been made private by its owner,
          you must be authenticated as the owner to view it.

    No user Authentication needed.
    """

    url = f"{USERS_URL}/{username}/wants"
    headers = user.headers
    params = user.params

    if page:
        params["page"] = max(1, page)
    if per_page:
        params["per_page"] = max(1, per_page)

    return requests.get(url, headers=headers, params=params)